### ISSUE TITLE
Error on export due to node reference

### ISSUE THREAD

**Issue by akielbowicz** [JuliaPluto/PlutoPDF.jl#1]
Hi I'm getting the following error when trying to use this package

```shell
julia> import PlutoExport
julia> PlutoExport.pdf("notebooks\\test_slider.jl")
[ Info: No output path provided. Defaulting to notebooks\test_slider.pdf
ERROR: IOError: could not spawn `node 'C:\Users\pc\.julia\packages\PlutoExport\mpDL0\node\bin.js' 'C:\Users\pc\Documents\Code\testing_pluto\notebooks\test_slider.jl' 'C:\Users\pc\Documents\Code\testing_pluto\notebooks\test_slider.pdf'`: no such file or directory (ENOENT)
Stacktrace:
 [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at .\process.jl:99
 [2] #585 at .\process.jl:112 [inlined]
 [3] setup_stdios(::Base.var"#585#586"{Cmd}, ::Array{Any,1}) at .\process.jl:196
 [4] _spawn at .\process.jl:111 [inlined]
 [5] run(::Cmd; wait::Bool) at .\process.jl:439
 [6] run at .\process.jl:438 [inlined]
 [7] pdf(::String, ::Nothing; console_output::Bool) at C:\Users\pc\.julia\packages\PlutoExport\mpDL0\src\PlutoExport.jl:38
 [8] pdf at C:\Users\pc\.julia\packages\PlutoExport\mpDL0\src\PlutoExport.jl:24 [inlined] (repeats 2 times)
 [9] top-level scope at REPL[4]:1
```

It seems like it doesn't find `node` which makes sense since [here](https://github.com/JuliaPluto/PlutoExport.jl/blob/397cb838f1ff33cee7b110697dc4a3cf2c433227/src/PlutoExport.jl#L36) it does not reference it through `NodeJS.nodejs_cmd()` but a global instance of it (which I do not have).

**Comment by akielbowicz** [comment]
Installing `node` seems to fix the error, but its not a solution.

I downloaded a copy of the repo and changed the reference to the one of NodeJS package and now I got this error: 

```shell
julia> import PlutoExport
julia> PlutoExport.pdf("..\notebooks\\test_slider.jl")
┌ Info: No output path provided. Defaulting to ..
└ otebooks\test_slider.pdf
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'puppeteer'
Require stack:
- C:\Users\pc\Documents\Code\testing_pluto\PlutoExport.jl\node\export.js
- C:\Users\pc\Documents\Code\testing_pluto\PlutoExport.jl\node\bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\pc\Documents\Code\testing_pluto\PlutoExport.jl\node\export.js:1:11)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\pc\\Documents\\Code\\testing_pluto\\PlutoExport.jl\\node\\export.js',
    'C:\\Users\\pc\\Documents\\Code\\testing_pluto\\PlutoExport.jl\\node\\bin.js'
  ]
}
ERROR: failed process: Process(`'C:\Users\pc\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node.exe' 'C:\Users\pc\Documents\Code\testing_pluto\PlutoExport.jl\node\bin.js' 'C:\Users\pc\Documents\Code\testing_pluto\PlutoExport.jl\..
otebooks\test_slider.jl' 'C:\Users\pc\Documents\Code\testing_pluto\PlutoExport.jl\..
otebooks\test_slider.pdf'`, ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error at .\process.jl:525 [inlined]
 [2] run(::Cmd; wait::Bool) at .\process.jl:440
 [3] run at .\process.jl:438 [inlined]
 [4] pdf(::String, ::Nothing; console_output::Bool) at C:\Users\pc\Documents\Code\testing_pluto\PlutoExport.jl\src\PlutoExport.jl:39
 [5] pdf at C:\Users\pc\Documents\Code\testing_pluto\PlutoExport.jl\src\PlutoExport.jl:25 [inlined] (repeats 2 times)
 [6] top-level scope at REPL[3]:1
```

Hope this info saves you some time. Node is way out of my knowledge and pay grade :P

**Comment by fonsp** [comment]
@akielbowicz Can you try again with the latest version?

**Comment by fonsp** [comment]
Fixed now
